---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
collections: 
upload_dir: images
public_path: images
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
